[project]
name = "byte-factory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pyyaml==6.0.3",
    "sv-ttk==2.6.1",
    "pyperclip>=1.8.2",
]
